-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- PROFILES (Managed by Supabase Auth, but we need a public table for roles)
CREATE TABLE public.profiles (
    id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
    email TEXT,
    kakao_id TEXT,
    name TEXT,
    phone TEXT,
    role TEXT CHECK (role IN ('owner', 'worker')), -- 'owner' or 'worker'
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS for profiles
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Profiles Policies
CREATE POLICY "Users can view own profile"
ON public.profiles FOR SELECT USING (auth.uid() = id);

CREATE POLICY "Users can insert their own profile" 
ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);

CREATE POLICY "Users can update own profile" 
ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- STORES (Owned by 'owner')
CREATE TABLE public.stores (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    owner_id UUID REFERENCES public.profiles(id) NOT NULL,
    name TEXT NOT NULL,
    address TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS for stores
ALTER TABLE public.stores ENABLE ROW LEVEL SECURITY;

-- Stores Policies
CREATE POLICY "Owners can view and edit their own stores" 
ON public.stores FOR ALL USING (auth.uid() = owner_id);

-- WORKERS (Link between User and Store)
CREATE TABLE public.workers (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id), -- Nullable initially if invited but not signed up? No, invitation flow handles this.
    store_id UUID REFERENCES public.stores(id) ON DELETE CASCADE NOT NULL,
    name TEXT NOT NULL,
    phone TEXT,
    hourly_wage NUMERIC DEFAULT 0,
    apply_weekly_allowance BOOLEAN DEFAULT FALSE,
    deduction_type TEXT CHECK (deduction_type IN ('withholding_3_3', 'four_insurance')) DEFAULT 'withholding_3_3',
    apply_night_allowance BOOLEAN DEFAULT FALSE,
    payday SMALLINT CHECK (payday BETWEEN 1 AND 31) DEFAULT 10,
    is_active BOOLEAN DEFAULT TRUE,
    joined_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS for workers
ALTER TABLE public.workers ENABLE ROW LEVEL SECURITY;

-- Workers Policies
CREATE POLICY "Owners can manage workers in their stores" 
ON public.workers FOR ALL USING (
    EXISTS (
        SELECT 1 FROM public.stores 
        WHERE stores.id = workers.store_id 
        AND stores.owner_id = auth.uid()
    )
);

CREATE POLICY "Workers can view their own record" 
ON public.workers FOR SELECT USING (auth.uid() = user_id);

-- Stores Policies (depends on workers table)
CREATE POLICY "Workers can view stores they belong to" 
ON public.stores FOR SELECT USING (
    EXISTS (
        SELECT 1 FROM public.workers 
        WHERE workers.store_id = stores.id 
        AND workers.user_id = auth.uid()
    )
);

-- INVITES (One-time or reusable links generated by Owner)
CREATE TABLE public.invites (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    store_id UUID REFERENCES public.stores(id) ON DELETE CASCADE NOT NULL,
    token TEXT UNIQUE NOT NULL, -- Used in deep link
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS for invites
ALTER TABLE public.invites ENABLE ROW LEVEL SECURITY;

-- Invites Policies
CREATE POLICY "Owners can create invites for their stores" 
ON public.invites FOR INSERT WITH CHECK (
    EXISTS (
        SELECT 1 FROM public.stores 
        WHERE stores.id = store_id 
        AND stores.owner_id = auth.uid()
    )
);

CREATE POLICY "Anyone with valid token can view invite (for onboarding)" 
ON public.invites FOR SELECT USING (true); -- Ideally restrictive but needed for anonymous onboarding lookup

-- WORK_LOGS (Attendance records)
CREATE TABLE public.work_logs (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    store_id UUID REFERENCES public.stores(id) ON DELETE CASCADE NOT NULL,
    worker_id UUID REFERENCES public.workers(id) ON DELETE CASCADE NOT NULL,
    check_in_at TIMESTAMPTZ NOT NULL,
    check_out_at TIMESTAMPTZ,
    status TEXT CHECK (status IN ('pending', 'approved', 'rejected')) DEFAULT 'pending',
    approved_by UUID REFERENCES public.profiles(id),
    approved_at TIMESTAMPTZ,
    applied_hourly_wage NUMERIC NOT NULL CHECK (applied_hourly_wage >= 0),
    applied_night_allowance BOOLEAN NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Freeze the wage terms that applied when each work log was created.
CREATE OR REPLACE FUNCTION public.set_work_log_payroll_snapshot()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    IF TG_OP = 'UPDATE'
       AND NEW.worker_id IS NOT DISTINCT FROM OLD.worker_id
       AND NEW.store_id IS NOT DISTINCT FROM OLD.store_id THEN
        NEW.applied_hourly_wage := OLD.applied_hourly_wage;
        NEW.applied_night_allowance := OLD.applied_night_allowance;
        RETURN NEW;
    END IF;

    SELECT
        GREATEST(COALESCE(w.hourly_wage, 0), 0),
        COALESCE(w.apply_night_allowance, FALSE)
    INTO
        NEW.applied_hourly_wage,
        NEW.applied_night_allowance
    FROM public.workers AS w
    WHERE w.id = NEW.worker_id
      AND w.store_id = NEW.store_id;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'worker does not belong to the selected store';
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER set_work_log_payroll_snapshot_trigger
BEFORE INSERT OR UPDATE ON public.work_logs
FOR EACH ROW
EXECUTE FUNCTION public.set_work_log_payroll_snapshot();

-- Keep temporal integrity for attendance records.
ALTER TABLE public.work_logs
ADD CONSTRAINT work_logs_checkout_after_checkin
CHECK (check_out_at IS NULL OR check_out_at >= check_in_at);

-- Allow multiple shifts per day, but prevent multiple concurrent open shifts.
CREATE UNIQUE INDEX work_logs_one_open_shift_per_worker_store
ON public.work_logs (store_id, worker_id)
WHERE check_out_at IS NULL;

-- Enable RLS for work_logs
ALTER TABLE public.work_logs ENABLE ROW LEVEL SECURITY;

-- Work Logs Policies
CREATE POLICY "Owners can manage logs for their stores" 
ON public.work_logs FOR ALL USING (
    EXISTS (
        SELECT 1 FROM public.stores 
        WHERE stores.id = work_logs.store_id 
        AND stores.owner_id = auth.uid()
    )
);

CREATE POLICY "Workers can view their own logs" 
ON public.work_logs FOR SELECT USING (
    EXISTS (
        SELECT 1 FROM public.workers 
        WHERE workers.id = work_logs.worker_id 
        AND workers.user_id = auth.uid()
    )
);

CREATE POLICY "Workers can insert/update their own logs (Check-in/out)" 
ON public.work_logs FOR INSERT WITH CHECK (
    EXISTS (
        SELECT 1 FROM public.workers 
        WHERE workers.id = worker_id 
        AND workers.user_id = auth.uid()
    )
);

-- Only allow update if it's the worker's own log and strictly for checkout (logic can be refined)
CREATE POLICY "Workers can update their own logs" 
ON public.work_logs FOR UPDATE USING (
    EXISTS (
        SELECT 1 FROM public.workers 
        WHERE workers.id = worker_id 
        AND workers.user_id = auth.uid()
    )
);

-- Function to handle new user signup (Trigger)
CREATE OR REPLACE FUNCTION public.handle_new_user() 
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, email)
  VALUES (new.id, new.email); -- Role set during onboarding
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();
